[package]
name = "learnpra"
version = "0.0.1"
authors = ["Arniu Tseng"]
description = "Learn by Practice"
repository = "https://github.com/arniu/learnpra"
license = "CC-BY-NC-ND-4.0"
readme = "README.md"
